name: Smart-Comments
version: 0.01
abstract: Comments that come to life
author: Damian Conway <damian@conway.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.0
  List::Util: 0
  Filter::Simple: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
