# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Smart-Comments
version:      v1.0.2
version_from: lib/Smart/Comments.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Filter::Simple:                0
    List::Util:                    0
    Test::More:                    0
    Text::Balanced:                0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
