---
name: Smart-Comments
version: 1.0.4
author:
  - 'Damian Conway <DCONWAY@cpan.org>'
abstract: Comments that do more than just sit there
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chorny/smart-comments/tree/master
requires:
  Data::Dumper: 0
  Filter::Simple: 0.8
  List::Util: 0
  Text::Balanced: 2
  perl: 5.008
  version: 0
build_requires:
  Test::More: 0
provides:
  Smart::Comments:
    file: lib/Smart/Comments.pm
    version: 1.0.4
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - Smart comments
  - perl debugging
  - development
